const alimentos = [
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Hipercalorico',
        nombre: 'Salsa Bolognesa',
        calorias: 451,
        proteinas: 18,
        carbohidratos: 55,
        lipidos: 8,
        precio: 508,
        gramaje: 172,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si',
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Cazuela de Vacuno',
        calorias: 343,
        proteinas: 28,
        carbohidratos: 36,
        lipidos: 10,
        precio: 656,
        gramaje: 355,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Carbonada de Vacuno',
        calorias: 300,
        proteinas: 22,
        carbohidratos: 33,
        lipidos: 9,
        precio: 600,
        gramaje: 295,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Chapsui de Vacuno',
        calorias: 272,
        proteinas: 34,
        carbohidratos: 18,
        lipidos: 7,
        precio: 960,
        gramaje: 313,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Charquicán de Carne',
        calorias: 304,
        proteinas: 19,
        carbohidratos: 38,
        lipidos: 8,
        precio: 725,
        gramaje: 420,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Estofado de Vacuno',
        calorias: 470,
        proteinas: 40,
        carbohidratos: 40,
        lipidos: 17,
        precio: 921,
        gramaje: 420,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pollo Arvejado',
        calorias: 436,
        proteinas: 49,
        carbohidratos: 36,
        lipidos: 10,
        precio: 1273,
        gramaje: 400,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pollo Asado',
        calorias: 238,
        proteinas: 26,
        carbohidratos: 3,
        lipidos: 13,
        precio: 550,
        gramaje: 140,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Cazuela de Ave',
        calorias: 614,
        proteinas: 72,
        carbohidratos: 41,
        lipidos: 18,
        precio: 1140,
        gramaje: 580,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pollo a la Plancha',
        calorias: 162,
        proteinas: 26,
        carbohidratos: 3,
        lipidos: 5,
        precio: 505,
        gramaje: 130,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Hipercalorico',
        nombre: 'Pescado Napolitano',
        calorias: 341,
        proteinas: 29,
        carbohidratos: 9,
        lipidos: 21,
        precio: 1030,
        gramaje: 260,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Tortilla de Porotos Verdes',
        calorias: 192,
        proteinas: 20,
        carbohidratos: 10,
        lipidos: 8,
        precio: 314,
        gramaje: 195,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Budín de Coliflor',
        calorias: 305,
        proteinas: 21,
        carbohidratos: 26,
        lipidos: 13,
        precio: 530,
        gramaje: 330,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Tortilla de Acelga',
        calorias: 192,
        proteinas: 20,
        carbohidratos: 10,
        lipidos: 8,
        precio: 310,
        gramaje: 260,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Flan de Zanahoria',
        calorias: 303,
        proteinas: 20,
        carbohidratos: 22,
        lipidos: 15,
        precio: 420,
        gramaje: 260,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Flan de Espinaca',
        calorias: 287,
        proteinas: 19,
        carbohidratos: 19,
        lipidos: 15,
        precio: 610,
        gramaje: 330,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Flan de Champignones',
        calorias: 271,
        proteinas: 18,
        carbohidratos: 16,
        lipidos: 15,
        precio: 680,
        gramaje: 245,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si',
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Budín de Zapallo Italiano',
        calorias: 301,
        proteinas: 20,
        carbohidratos: 26,
        lipidos: 13,
        precio: 500,
        gramaje: 377,
        categoria: 'Alto en Carbohidrato',
        acompanamiento: 'si',
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Tortilla Finas Hierbas',
        calorias: 194,
        proteinas: 23,
        carbohidratos: 5,
        lipidos: 9,
        precio: 390,
        gramaje: 158,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Hipercalorico',
        nombre: 'Leche con Maicena',
        calorias: 298,
        proteinas: 5,
        carbohidratos: 56,
        lipidos: 6,
        precio: 260,
        gramaje: 250,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Hipercalorico',
        nombre: 'Leche con Avena',
        calorias: 282,
        proteinas: 10,
        carbohidratos: 43,
        lipidos: 8,
        precio: 170,
        gramaje: 240,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Frutas',
        nombre: 'Tutti Frutti',
        calorias: 142,
        proteinas: 1,
        carbohidratos: 34,
        lipidos: 0,
        precio: 190,
        gramaje: 165,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Hipercalorico',
        nombre: 'Leche Asada',
        calorias: 241,
        proteinas: 14,
        carbohidratos: 36,
        lipidos: 5,
        precio: 170,
        gramaje: 180,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Lacteo',
        nombre: 'Leche con Sémola',
        calorias: 168,
        proteinas: 4,
        carbohidratos: 31,
        lipidos: 3,
        precio: 100,
        gramaje: 130,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Postre',
        tipo: 'Lacteo',
        nombre: 'Leche con Arroz',
        calorias: 168,
        proteinas: 3,
        carbohidratos: 32,
        lipidos: 3,
        precio: 180,
        gramaje: 140,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Pasta',
        nombre: 'Tallarines',
        calorias: 135,
        proteinas: 2,
        carbohidratos: 19,
        lipidos: 6,
        precio: 160,
        gramaje: 75,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Pasta',
        nombre: 'Espirales en Salsa de Champiñones',
        calorias: 345,
        proteinas: 8,
        carbohidratos: 34,
        lipidos: 20,
        precio: 510,
        gramaje: 255,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Arroz Primavera',
        calorias: 210,
        proteinas: 3,
        carbohidratos: 25,
        lipidos: 11,
        precio: 150,
        gramaje: 320,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Arroz Perla',
        calorias: 144,
        proteinas: 2,
        carbohidratos: 21,
        lipidos: 6,
        precio: 70,
        gramaje: 225,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Pancutras',
        calorias: 302,
        proteinas: 23,
        carbohidratos: 26,
        lipidos: 12,
        precio: 560,
        gramaje: 155,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Hipercalorico', 
        nombre: 'Puré de Papas',
        calorias: 383,
        proteinas: 7,
        carbohidratos: 62,
        lipidos: 12,
        precio: 230,
        gramaje: 360,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Hipercalorico', 
        nombre: 'Papas Duquesas',
        calorias: 262,
        proteinas: 9,
        carbohidratos: 47,
        lipidos: 3,
        precio: 240,
        gramaje: 320,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Leguminosas',
        nombre: 'Porotos Granados',
        calorias: 308,
        proteinas: 14,
        carbohidratos: 49,
        lipidos: 6,
        precio: 500,
        gramaje: 275,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Leguminosas',
        nombre: 'Porotos a la Chilena',
        calorias: 402,
        proteinas: 20,
        carbohidratos: 66,
        lipidos: 7,
        precio: 270,
        gramaje: 175,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Guiso de Arvejas',
        calorias: 379,
        proteinas: 19,
        carbohidratos: 60,
        lipidos: 7,
        precio: 300,
        gramaje: 165,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Leguminosas',
        nombre: 'Garbanzos con Arroz',
        calorias: 402,
        proteinas: 17,
        carbohidratos: 61,
        lipidos: 10,
        precio: 300,
        gramaje: 165,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Leguminosas',
        nombre: 'Ensalada de Porotos',
        calorias: 257,
        proteinas: 13,
        carbohidratos: 38,
        lipidos: 6,
        precio: 200,
        gramaje: 105,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Puré de Porotos',
        calorias: 364,
        proteinas: 21,
        carbohidratos: 58,
        lipidos: 5,
        precio: 240,
        gramaje: 115,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Puré de Lentejas',
        calorias: 386,
        proteinas: 28,
        carbohidratos: 57,
        lipidos: 5,
        precio: 220,
        gramaje: 115,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Sopa',
        nombre: 'Puré de Garbanzos',
        calorias: 414,
        proteinas: 20,
        carbohidratos: 61,
        lipidos: 10,
        precio: 250,
        gramaje: 115,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pollo con Verduras',
        calorias: 129,
        proteinas: 12,
        carbohidratos: 7,
        lipidos: 6,
        precio: 450,
        gramaje: 130,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Huevo',
        nombre: 'Ensalada de Espinaca y Palmito',
        calorias: 202,
        proteinas: 12,
        carbohidratos: 16,
        lipidos: 10,
        precio: 550,
        gramaje: 300,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Lacteo',
        nombre: 'Ensalada Multicolor',
        calorias: 197,
        proteinas: 10,
        carbohidratos: 10,
        lipidos: 13,
        precio: 600,
        gramaje: 307,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Lacteo',
        nombre: 'Ensalada Griega',
        calorias: 175,
        proteinas: 10,
        carbohidratos: 10,
        lipidos: 9,
        precio: 430,
        gramaje: 245,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Albondiguillas de Pavo horneadas',
        calorias: 158,
        proteinas: 10,
        carbohidratos: 4,
        lipidos: 11,
        precio: 250,
        gramaje: 70,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'si',
        },
    {
        horario: 'Colacion',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Tostadas con huevo revuelto',
        calorias: 160,
        proteinas: 11,
        carbohidratos: 12,
        lipidos: 9,
        precio: 400,
        gramaje: 75,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si'
        },
    {
        horario: 'Colacion',
        plato: 'Fondo',
        tipo: 'Vegetariano',
        nombre: 'Tostadas integrales con palta',
        calorias: 190,
        proteinas: 4,
        carbohidratos: 15,
        lipidos: 14,
        precio: 450,
        gramaje: 70,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'si',
        },
    {
        horario: 'Colacion',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Yogurt descremado con frutos secos',
        calorias: 190,
        proteinas: 10,
        carbohidratos: 12,
        lipidos: 10,
        precio: 500,
        gramaje: 115,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Colacion',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Mix frutos rojos y chia con yogurt',
        calorias: 160,
        proteinas: 8,
        carbohidratos: 18,
        lipidos: 5,
        precio: 550,
        gramaje: 115,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Once',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Tostadas con ave pimenton',
        calorias: 170,
        proteinas: 13,
        carbohidratos: 12,
        lipidos: 7,
        precio: 600,
        gramaje: 70,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Vegetariano',
        nombre: 'Ensalada Chilena',
        calorias: 52,
        proteinas: 2,
        carbohidratos: 7,
        lipidos: 3,
        precio: 800,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Pasta',
        nombre: 'Ensalada Griega con Pastas',
        calorias: 255,
        proteinas: 5,
        carbohidratos: 27,
        lipidos: 14,
        precio: 700,
        gramaje: 225,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Leguminosas',
        nombre: 'Ensalada de Lentejas con Apio',
        calorias: 370,
        proteinas: 14,
        carbohidratos: 40,
        lipidos: 16,
        precio: 930,
        gramaje: 405,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Sopa',
        nombre: 'Crema de Apio',
        calorias: 170,
        proteinas: 4,
        carbohidratos: 10,
        lipidos: 13,
        precio: 500,
        gramaje: 250,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'no',
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Piña',
        calorias: 59,
        proteinas: 1,
        carbohidratos: 15,
        lipidos: 1,
        precio: 410,
        gramaje: 120,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Piña Enlatada',
        calorias: 62,
        proteinas: 0,
        carbohidratos: 16,
        lipidos: 0,
        precio: 270,
        gramaje: 80,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Plátano',
        calorias: 55,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 0,
        precio: 200,
        gramaje: 60,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Sandía',
        calorias: 64,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 1,
        precio: 340,
        gramaje: 200,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Tuna',
        calorias: 62,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 1,
        precio: 510,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Uvas',
        calorias: 57,
        proteinas: 1,
        carbohidratos: 16,
        lipidos: 0,
        precio: 310,
        gramaje: 90,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Bebestible',
        tipo: 'Fruta',
        nombre: 'Limonada',
        calorias: 38,
        proteinas: 1,
        carbohidratos: 13,
        lipidos: 0,
        precio: 510,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Cualquiera',
        plato: 'Bebestible',
        tipo: 'Fruta',
        nombre: 'Jugo de Naranja',
        calorias: 67,
        proteinas: 1,
        carbohidratos: 16,
        lipidos: 0,
        precio: 410,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Bebestible',
        tipo: 'Fruta',
        nombre: 'Jugo de Pomelo',
        calorias: 59,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 0,
        precio: 410,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cena',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Ensalada de Porotos verdes, Choclos y Habas',
        calorias: 126,
        proteinas: 9,
        carbohidratos: 19,
        lipidos: 1,
        precio: 560,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Cena',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Ensalada de tomate, champiñon y palmito',
        calorias: 47,
        proteinas: 3,
        carbohidratos: 7,
        lipidos: 2,
        precio: 790,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Cena',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Ensalada de lechuga, zanahoria y pepino',
        calorias: 34,
        proteinas: 1,
        carbohidratos: 7,
        lipidos: 0,
        precio: 440,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Omelette de Claras y Espinaca',
        calorias: 120,
        proteinas: 18,
        carbohidratos: 3,
        lipidos: 2,
        precio: 400,
        gramaje: 120,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Desayuno',
        plato: 'Acompañamiento',
        tipo: 'Lacteo',
        nombre: 'Yogurt Griego Natural con almendras',
        calorias: 190,
        proteinas: 17,
        carbohidratos: 8,
        lipidos: 10,
        precio: 600,
        gramaje: 130,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
        },
    {
        horario: 'Desayuno',
        plato: 'Acompañamiento',
        tipo: 'Huevo',
        nombre: 'Panqueques de Avena y claras',
        calorias: 230,
        proteinas: 18,
        carbohidratos: 20,
        lipidos: 6,
        precio: 500,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no',
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Huevo revuelto con Jamon de Pavo',
        calorias: 200,
        proteinas: 19,
        carbohidratos: 2,
        lipidos: 10,
        precio: 600,
        gramaje: 100,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Burrito integral con Pollo',
        calorias: 280,
        proteinas: 21,
        carbohidratos: 25,
        lipidos: 9,
        precio: 950,
        gramaje: 110,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Lacteo',
        nombre: 'Arepa de avena y Quesillo',
        calorias: 250,
        proteinas: 16,
        carbohidratos: 22,
        lipidos: 8,
        precio: 700,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'si'
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Sándwich de pan integral con atún light',
        calorias: 270,
        proteinas: 21,
        carbohidratos: 22,
        lipidos: 7,
        precio: 750,
        gramaje: 180,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Huevo',
        nombre: 'Tortilla de Brócoli',
        calorias: 230,
        proteinas: 18,
        carbohidratos: 12,
        lipidos: 10,
        precio: 600,
        gramaje: 150,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Desayuno',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pan pita integral con pechuga de pollo',
        calorias: 280,
        proteinas: 22,
        carbohidratos: 23,
        lipidos: 8,
        precio: 800,
        gramaje: 170,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si',
        },
    {
        horario: 'Cualquiera',
        plato: 'Acompañamiento',
        tipo: 'Huevo',
        nombre: 'Huevo Duro',
        calorias: 78,
        proteinas: 6,
        carbohidratos: 1,
        lipidos: 5,
        precio: 150,
        gramaje: 50,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
        },
    {
        horario: 'Colacion',
        plato: 'Acompañamiento',
        tipo: 'Lacteo',
        nombre: 'Yogurt Griego Natural',
        calorias: 100,
        proteinas: 10,
        carbohidratos: 6,
        lipidos: 4,
        precio: 400,
        gramaje: 120,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Acompañamiento',
        tipo: 'Pescado',
        nombre: 'Atún en agua',
        calorias: 90,
        proteinas: 20,
        carbohidratos: 0,
        lipidos: 1,
        precio: 500,
        gramaje: 80,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Acompañamiento',
        tipo: 'Lacteo',
        nombre: 'Quesillo',
        calorias: 100,
        proteinas: 12,
        carbohidratos: 2,
        lipidos: 5,
        precio: 400,
        gramaje: 80,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
        },
    {
        horario: 'Colacion',
        plato: 'Acompañamiento',
        tipo: 'Vegetariano',
        nombre: 'Mix Frutos Secos',
        calorias: 200,
        proteinas: 7,
        carbohidratos: 8,
        lipidos: 15,
        precio: 600,
        gramaje: 30,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Vegetariano',
        nombre: 'Ensalada a la Chilena',
        calorias: 112,
        proteinas: 3,
        carbohidratos: 16,
        lipidos: 5,
        precio: 800,
        gramaje: 250,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cena',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Budín de Jurel',
        calorias: 422,
        proteinas: 37,
        carbohidratos: 17,
        lipidos: 22,
        precio: 1050,
        gramaje: 305,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Tomaticán',
        calorias: 320,
        proteinas: 29,
        carbohidratos: 11,
        lipidos: 18,
        precio: 2300,
        gramaje: 520,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Pasta',
        nombre: 'Ensalada Griega con Pastas',
        calorias: 255,
        proteinas: 5,
        carbohidratos: 27,
        lipidos: 14,
        precio: 700,
        gramaje: 225,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Leguminosas',
        nombre: 'Ensalada de Lentejas con Apio',
        calorias: 370,
        proteinas: 14,
        carbohidratos: 40,
        lipidos: 16,
        precio: 930,
        gramaje: 405,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Sopa',
        nombre: 'Crema de Apio',
        calorias: 170,
        proteinas: 4,
        carbohidratos: 10,
        lipidos: 13,
        precio: 500,
        gramaje: 250,
        categoria: 'Alto en Lipidos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Vacuno',
        nombre: 'Charquicán',
        calorias: 352,
        proteinas: 22,
        carbohidratos: 32,
        lipidos: 15,
        precio: 1300,
        gramaje: 400,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Croquetas de Atún',
        calorias: 220,
        proteinas: 22,
        carbohidratos: 12,
        lipidos: 10,
        precio: 400,
        gramaje: 160,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Cerezas',
        calorias: 65,
        proteinas: 1,
        carbohidratos: 15,
        lipidos: 1,
        precio: 500,
        gramaje: 90,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Chirimoya',
        calorias: 50,
        proteinas: 3,
        carbohidratos: 11,
        lipidos: 1,
        precio: 260,
        gramaje: 90,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Ciruelas',
        calorias: 61,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 1,
        precio: 380,
        gramaje: 110,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Damasco',
        calorias: 58,
        proteinas: 2,
        carbohidratos: 13,
        lipidos: 1,
        precio: 410,
        gramaje: 120,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Durazno',
        calorias: 56,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 0,
        precio: 450,
        gramaje: 130,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Durazno en conserva',
        calorias: 59,
        proteinas: 1,
        carbohidratos: 16,
        lipidos: 0,
        precio: 280,
        gramaje: 80,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Frambuesa',
        calorias: 64,
        proteinas: 1,
        carbohidratos: 15,
        lipidos: 1,
        precio: 890,
        gramaje: 130,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Frutilla',
        calorias: 60,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 1,
        precio: 1360,
        gramaje: 200,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Kiwi',
        calorias: 61,
        proteinas: 1,
        carbohidratos: 15,
        lipidos: 0,
        precio: 340,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Manzana',
        calorias: 59,
        proteinas: 0,
        carbohidratos: 15,
        lipidos: 0,
        precio: 240,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Melon',
        calorias: 63,
        proteinas: 2,
        carbohidratos: 15,
        lipidos: 1,
        precio: 310,
        gramaje: 180,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Membrillo',
        calorias: 57,
        proteinas: 0,
        carbohidratos: 15,
        lipidos: 0,
        precio: 310,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Mora',
        calorias: 62,
        proteinas: 1,
        carbohidratos: 15,
        lipidos: 1,
        precio: 820,
        gramaje: 120,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Naranja',
        calorias: 56,
        proteinas: 1,
        carbohidratos: 14,
        lipidos: 0,
        precio: 310,
        gramaje: 120,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Cualquiera',
        plato: 'Postre',
        tipo: 'Fruta',
        nombre: 'Pera',
        calorias: 59,
        proteinas: 0,
        carbohidratos: 15,
        lipidos: 0,
        precio: 310,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
        },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pastel Reina',
        calorias: 322,
        proteinas: 29,
        carbohidratos: 39,
        lipidos: 5,
        precio: 608,
        gramaje: 210,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Chapsui de Ave',
        calorias: 332,
        proteinas: 43,
        carbohidratos: 22,
        lipidos: 8,
        precio: 1033,
        gramaje: 393,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Pollo al Jugo',
        calorias: 185,
        proteinas: 28,
        carbohidratos: 7,
        lipidos: 5,
        precio: 555,
        gramaje: 230,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Pescado al Vapor',
        calorias: 132,
        proteinas: 21,
        carbohidratos: 3,
        lipidos: 4,
        precio: 827,
        gramaje: 160,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Pescado al Jugo',
        calorias: 148,
        proteinas: 22,
        carbohidratos: 6,
        lipidos: 4,
        precio: 856,
        gramaje: 210,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Pescado al Horno',
        calorias: 204,
        proteinas: 21,
        carbohidratos: 3,
        lipidos: 12,
        precio: 855,
        gramaje: 180,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Pescado al Campignon',
        calorias: 342,
        proteinas: 23,
        carbohidratos: 13,
        lipidos: 22,
        precio: 1100,
        gramaje: 275,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Almuerzo',
        plato: 'Fondo',
        tipo: 'Pescado',
        nombre: 'Pescado a la plancha',
        calorias: 132,
        proteinas: 21,
        carbohidratos: 3,
        lipidos: 4,
        precio: 925,
        gramaje: 160,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Colacion',
        plato: 'Fondo',
        tipo: 'Ave',
        nombre: 'Rollitos de Pollo y Palta',
        calorias: 180,
        proteinas: 17,
        carbohidratos: 5,
        lipidos: 8,
        precio: 700,
        gramaje: 90,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'si'
    },
    {
        horario: 'Cualquiera',
        plato: 'Bebestible',
        tipo: 'Lacteo',
        nombre: 'Leche descremada',
        calorias: 90,
        proteinas: 8,
        carbohidratos: 12,
        lipidos: 2,
        precio: 350,
        gramaje: 200,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Ave',
        nombre: 'Ensalada de Pollo y Tomatillo',
        calorias: 141,
        proteinas: 16,
        carbohidratos: 12,
        lipidos: 4,
        precio: 1200,
        gramaje: 340,
        categoria: 'Alto en Proteinas',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Vegetariano',
        nombre: 'Ensalada de Pepino',
        calorias: 39,
        proteinas: 1,
        carbohidratos: 8,
        lipidos: 0,
        precio: 500,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Vegetariano',
        nombre: 'Ensalada de Lechuga, Tomate y Cebolla',
        calorias: 89,
        proteinas: 1,
        carbohidratos: 10,
        lipidos: 5,
        precio: 700,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Entrada',
        tipo: 'Leguminosas',
        nombre: 'Ensalada de Lentejas y Atún',
        calorias: 185,
        proteinas: 15,
        carbohidratos: 20,
        lipidos: 5,
        precio: 1000,
        gramaje: 240,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Pasta',
        nombre: 'Fideos Integrales',
        calorias: 244,
        proteinas: 10,
        carbohidratos: 47,
        lipidos: 2,
        precio: 500,
        gramaje: 80,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Arroz Integral',
        calorias: 111,
        proteinas: 3,
        carbohidratos: 23,
        lipidos: 1,
        precio: 400,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Cuscús Integral',
        calorias: 112,
        proteinas: 4,
        carbohidratos: 23,
        lipidos: 1,
        precio: 600,
        gramaje: 110,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Papas Cocidas',
        calorias: 116,
        proteinas: 3,
        carbohidratos: 26,
        lipidos: 0,
        precio: 300,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Quinoa Natural',
        calorias: 120,
        proteinas: 4,
        carbohidratos: 21,
        lipidos: 2,
        precio: 800,
        gramaje: 100,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Almuerzo',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Puré de Papas sin Mantequilla',
        calorias: 160,
        proteinas: 4,
        carbohidratos: 35,
        lipidos: 2,
        precio: 300,
        gramaje: 200,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    },
    {
        horario: 'Cena',
        plato: 'Acompañamiento',
        tipo: 'Cereal',
        nombre: 'Choclo cocido en granos',
        calorias: 130,
        proteinas: 4,
        carbohidratos: 28,
        lipidos: 2,
        precio: 350,
        gramaje: 150,
        categoria: 'Alto en CarboHidratos',
        acompanamiento: 'no'
    }
];
    